// <auto-generated />
using ApiPaliNumb.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiPaliNumb.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250625045525_AddNumeroAndPalindromo")]
    partial class AddNumeroAndPalindromo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiPaliNumb.Infrastructure.Numero", b =>
                {
                    b.Property<int>("Valor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Valor"));

                    b.Property<bool>("EsPar")
                        .HasColumnType("bit");

                    b.HasKey("Valor");

                    b.ToTable("Numeros");
                });

            modelBuilder.Entity("ApiPaliNumb.Infrastructure.Palindromo", b =>
                {
                    b.Property<string>("Texto")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("EsPalindromo")
                        .HasColumnType("bit");

                    b.HasKey("Texto");

                    b.ToTable("Palindromos");
                });

            modelBuilder.Entity("ApiPaliNumb.Infrastructure.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
